import os
import sys
import re
import subprocess
import tempfile
import tkinter as tk
from tkinter import filedialog, messagebox, ttk

# ================= CROSS-PLATFORM SETTINGS =================
IS_WIN = sys.platform == "win32"

# Dynamic Fonts based on OS
FONT_UI = ("Segoe UI", 10) if IS_WIN else ("Helvetica", 10)
FONT_UI_BOLD = ("Segoe UI", 10, "bold") if IS_WIN else ("Helvetica", 10, "bold")
FONT_UI_H = ("Segoe UI", 11, "bold") if IS_WIN else ("Helvetica", 11, "bold")
FONT_BTN = ("Segoe UI", 9, "bold") if IS_WIN else ("Helvetica", 9, "bold")
FONT_CODE = ("Consolas", 10) if IS_WIN else ("monospace", 10)
FONT_CODE_L = ("Consolas", 11) if IS_WIN else ("monospace", 11)
# ===========================================================

# --- ANSI Escape Code Remover ---
ANSI_REGEX = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")


def strip_ansi(text: str) -> str:
    """Removes ANSI color codes generated by C executable."""
    return ANSI_REGEX.sub("", text)


class SQLValidatorApp:

    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("SQL Query Validator & AST Visualizer")
        self.root.geometry("1100x700")
        self.root.minsize(800, 500)
        self.root.configure(bg="#1f2329")

        # Locate executable cross-platform
        self.exe_path = self.find_executable()

        # UI Styling & Theme
        self.style = ttk.Style()
        self.style.theme_use("clam")
        self.configure_styles()

        # Build Main UI
        self.create_toolbar()
        self.create_main_layout()
        self.create_statusbar()

        # Load initial sample query
        self.load_sample("Basic SELECT Query")

    def find_executable(self) -> str:
        """Finds the compiled C binary strictly based on the OS."""
        if IS_WIN:
            # Windows strictly looks for the .exe
            candidates = ["sql_validator.exe", ".\\sql_validator.exe"]
            default = "sql_validator.exe"
        else:
            # Linux/macOS strictly looks for the extensionless binary
            candidates = ["sql_validator", "./sql_validator"]
            default = "sql_validator"
            
        for cand in candidates:
            if os.path.exists(cand):
                return os.path.abspath(cand)
                
        # If not found, return the OS-specific default for error messages
        return default

    def configure_styles(self):
        self.style.configure("TFrame", background="#1f2329")
        self.style.configure("TLabel", background="#1f2329", foreground="#d7dae0", font=FONT_UI)
        self.style.configure("Header.TLabel", font=FONT_UI_H, foreground="#61afef")
        self.style.configure("TButton", font=FONT_BTN, padding=6)
        self.style.configure("TCheckbutton", background="#1f2329", foreground="#d7dae0")
        self.style.configure("TNotebook", background="#1f2329", tabmargins=[2, 5, 2, 0])
        self.style.configure("TNotebook.Tab", background="#242a33", foreground="#d7dae0", padding=[12, 6])
        self.style.map(
            "TNotebook.Tab",
            background=[("selected", "#2e98f5")],
            foreground=[("selected", "#ffffff")],
        )

        self.style.configure("Card.TFrame", background="#242a33", relief="flat")
        self.style.configure("Card.TLabel", background="#242a33", foreground="#d7dae0", font=FONT_UI)
        self.style.configure("CardHeader.TLabel", background="#242a33", foreground="#61afef", font=FONT_UI_H)
        self.style.configure("Accent.TLabel", background="#1f2329", foreground="#61afef", font=FONT_UI_BOLD)

        # Treeview styling
        self.style.configure(
            "Treeview",
            background="#1f2933",
            fieldbackground="#1f2933",
            foreground="#d7dae0",
            font=FONT_CODE,
            rowheight=24,
            bordercolor="#313846",
            lightcolor="#313846",
            darkcolor="#313846",
        )
        self.style.map(
            "Treeview",
            background=[("selected", "#3e526d")],
            foreground=[("selected", "#ffffff")],
        )

    def create_toolbar(self):
        toolbar = ttk.Frame(self.root, padding=10, style="Card.TFrame")
        toolbar.pack(side=tk.TOP, fill=tk.X, padx=10, pady=(10, 0))

        left_container = ttk.Frame(toolbar, style="Card.TFrame")
        left_container.pack(side=tk.LEFT, fill=tk.X, expand=True)

        ttk.Label(left_container, text="Sample Queries:", style="Accent.TLabel").pack(side=tk.LEFT, padx=(0, 6))
        self.sample_var = tk.StringVar(value="Basic SELECT Query")
        samples = [
            "Basic SELECT Query",
            "SELECT with JOIN & GROUP BY",
            "CREATE TABLE with Constraints",
            "INSERT INTO Values",
            "Transaction Control (TCL)",
            "Invalid Syntax Error Demo",
        ]
        sample_menu = ttk.Combobox(
            left_container,
            textvariable=self.sample_var,
            values=samples,
            state="readonly",
            width=28,
            font=FONT_UI,
        )
        sample_menu.pack(side=tk.LEFT, padx=(0, 14))
        sample_menu.bind("<<ComboboxSelected>>", lambda e: self.load_sample(self.sample_var.get()))

        btn_run = tk.Button(
            toolbar,
            text="▶ Run / Validate",
            bg="#61afef",
            fg="#1e1e1e",
            font=FONT_BTN,
            padx=12,
            relief=tk.FLAT,
            activebackground="#4a90e2",
            activeforeground="#ffffff",
            command=self.validate_sql,
        )
        btn_run.pack(side=tk.LEFT, padx=(0, 8))

        # Replaced failing emojis with standard text for Linux compatibility
        btn_open = ttk.Button(toolbar, text="Open File", command=self.open_file)
        btn_open.pack(side=tk.LEFT, padx=4)

        btn_clear = ttk.Button(toolbar, text="Clear", command=self.clear_editor)
        btn_clear.pack(side=tk.LEFT, padx=4)

        flag_container = ttk.Frame(toolbar, style="Card.TFrame")
        flag_container.pack(side=tk.RIGHT, anchor=tk.E)

        self.show_tokens_var = tk.BooleanVar(value=False)
        chk_tokens = ttk.Checkbutton(flag_container, text="Include Lexer Tokens (--tokens)", variable=self.show_tokens_var)
        chk_tokens.pack(side=tk.RIGHT)

    def create_main_layout(self):
        paned = ttk.PanedWindow(self.root, orient=tk.HORIZONTAL)
        paned.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

        # ================= LEFT PANEL =================
        left_frame = ttk.Frame(paned, padding=10, style="Card.TFrame")
        paned.add(left_frame, weight=1)

        ttk.Label(left_frame, text="SQL Input Editor", style="CardHeader.TLabel").pack(anchor=tk.W, pady=(0, 8))

        self.editor = tk.Text(
            left_frame,
            wrap=tk.NONE,
            font=FONT_CODE_L,
            bg="#171b20",
            fg="#d7dae0",
            insertbackground="#ffffff",
            relief=tk.FLAT,
            padx=10,
            pady=10,
            undo=True,
            borderwidth=0,
            highlightthickness=1,
            highlightbackground="#313846",
            highlightcolor="#61afef",
        )

        edit_sb_y = ttk.Scrollbar(left_frame, orient=tk.VERTICAL, command=self.editor.yview)
        edit_sb_x = ttk.Scrollbar(left_frame, orient=tk.HORIZONTAL, command=self.editor.xview)
        self.editor.configure(yscrollcommand=edit_sb_y.set, xscrollcommand=edit_sb_x.set)

        edit_sb_y.pack(side=tk.RIGHT, fill=tk.Y)
        edit_sb_x.pack(side=tk.BOTTOM, fill=tk.X)
        self.editor.pack(fill=tk.BOTH, expand=True)

        # ================= RIGHT PANEL =================
        right_frame = ttk.Frame(paned, padding=10, style="Card.TFrame")
        paned.add(right_frame, weight=1)

        self.notebook = ttk.Notebook(right_frame)
        self.notebook.pack(fill=tk.BOTH, expand=True)

        self.tab_tree = ttk.Frame(self.notebook, style="Card.TFrame")
        # Replaced emojis with standard geometric shapes
        self.notebook.add(self.tab_tree, text=" ❖ Visual AST Tree")
        self.create_tree_tab()

        self.tab_output = ttk.Frame(self.notebook, style="Card.TFrame")
        self.notebook.add(self.tab_output, text=" ≡ Console Output")
        self.create_output_tab()

    def create_tree_tab(self):
        tree_frame = ttk.Frame(self.tab_tree, padding=8, style="Card.TFrame")
        tree_frame.pack(fill=tk.BOTH, expand=True, padx=2, pady=2)

        self.ast_tree = ttk.Treeview(tree_frame, selectmode="browse", show="tree")
        tree_sb_y = ttk.Scrollbar(tree_frame, orient=tk.VERTICAL, command=self.ast_tree.yview)
        tree_sb_x = ttk.Scrollbar(tree_frame, orient=tk.HORIZONTAL, command=self.ast_tree.xview)
        self.ast_tree.configure(yscrollcommand=tree_sb_y.set, xscrollcommand=tree_sb_x.set)

        tree_sb_y.pack(side=tk.RIGHT, fill=tk.Y)
        tree_sb_x.pack(side=tk.BOTTOM, fill=tk.X)
        self.ast_tree.pack(fill=tk.BOTH, expand=True)

    def create_output_tab(self):
        out_frame = ttk.Frame(self.tab_output, padding=8, style="Card.TFrame")
        out_frame.pack(fill=tk.BOTH, expand=True, padx=2, pady=2)

        self.console_output = tk.Text(
            out_frame,
            wrap=tk.NONE,
            font=FONT_CODE,
            bg="#171b20",
            fg="#d7dae0",
            insertbackground="#ffffff",
            relief=tk.FLAT,
            padx=10,
            pady=10,
            borderwidth=0,
            highlightthickness=1,
            highlightbackground="#313846",
        )

        out_sb_y = ttk.Scrollbar(out_frame, orient=tk.VERTICAL, command=self.console_output.yview)
        out_sb_x = ttk.Scrollbar(out_frame, orient=tk.HORIZONTAL, command=self.console_output.xview)
        self.console_output.configure(yscrollcommand=out_sb_y.set, xscrollcommand=out_sb_x.set)

        out_sb_y.pack(side=tk.RIGHT, fill=tk.Y)
        out_sb_x.pack(side=tk.BOTTOM, fill=tk.X)
        self.console_output.pack(fill=tk.BOTH, expand=True)

        self.console_output.tag_config("success", foreground="#98c379", font=(FONT_CODE[0], 10, "bold"))
        self.console_output.tag_config("error", foreground="#e06c75", font=(FONT_CODE[0], 10, "bold"))
        self.console_output.tag_config("header", foreground="#61afef", font=(FONT_CODE[0], 10, "bold"))

    def create_statusbar(self):
        self.statusbar = ttk.Frame(self.root, padding=(10, 8), style="Card.TFrame")
        self.statusbar.pack(side=tk.BOTTOM, fill=tk.X, padx=10, pady=(0, 10))

        self.status_badge = tk.Label(
            self.statusbar,
            text=" READY ",
            bg="#61afef",
            fg="#1e1e1e",
            font=FONT_BTN,
            padx=8,
            pady=4,
            relief=tk.FLAT,
            bd=0,
        )
        self.status_badge.pack(side=tk.LEFT)

        self.status_label = ttk.Label(self.statusbar, text=f" Executable: {os.path.basename(self.exe_path)}", style="CardHeader.TLabel")
        self.status_label.pack(side=tk.LEFT, padx=12)

    def validate_sql(self):
        query = self.editor.get("1.0", tk.END).strip()
        if not query:
            messagebox.showwarning("Empty Query", "Please enter a SQL query to validate.")
            return

        if not os.path.exists(self.exe_path):
            messagebox.showerror(
                "Executable Not Found",
                f"Could not find '{self.exe_path}'.\n\nPlease compile the C code first using gcc or make!",
            )
            return

        with tempfile.NamedTemporaryFile(mode="w", suffix=".sql", delete=False, encoding="utf-8") as tmp:
            tmp.write(query)
            tmp_path = tmp.name

        try:
            cmd = [self.exe_path, "--ast", "-f", tmp_path]
            if self.show_tokens_var.get():
                cmd.insert(1, "--tokens")

            process = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, encoding="utf-8", errors="replace"
            )
            stdout, stderr = process.communicate()

            clean_out = strip_ansi(stdout + stderr)

            self.console_output.delete("1.0", tk.END)

            if "SUCCESS" in clean_out:
                self.status_badge.config(text=" VALID SQL ", bg="#98c379", fg="#1e1e1e")
                self.status_label.config(text=" Query parsed successfully without syntax errors.")
                self.console_output.insert(tk.END, clean_out)
                self.notebook.select(self.tab_tree) 
            else:
                self.status_badge.config(text=" SYNTAX ERROR ", bg="#e06c75", fg="#ffffff")
                self.status_label.config(text=" Syntax error detected! Check console output for caret position.")
                self.console_output.insert(tk.END, clean_out, "error")
                self.notebook.select(self.tab_output) 

            self.populate_ast_treeview(clean_out)

        except Exception as e:
            messagebox.showerror("Execution Error", str(e))
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    def populate_ast_treeview(self, raw_output: str):
        for item in self.ast_tree.get_children():
            self.ast_tree.delete(item)

        if "ABSTRACT SYNTAX TREE" not in raw_output:
            return

        ast_lines = []
        capture = False
        for line in raw_output.splitlines():
            if "ABSTRACT SYNTAX TREE" in line:
                capture = True
                continue
            if capture:
                if "=======================================================" in line:
                    if ast_lines: break
                    else: continue
                if line.strip(): ast_lines.append(line)

        if not ast_lines:
            return

        root_label = ast_lines[0].strip()
        # Replaced root emoji with basic unicode
        root_id = self.ast_tree.insert("", tk.END, text=f" ■ {root_label}", open=True)

        stack = [(0, root_id)]

        for line in ast_lines[1:]:
            prefix_match = re.match(r"^([│\s├└─]+)", line)
            if not prefix_match:
                continue

            prefix = prefix_match.group(1)
            depth = len(prefix) // 4

            node_label = line[len(prefix) :].strip()
            if not node_label: continue

            # Replaced node emojis with basic unicode geometric shapes for Linux support
            icon = "○"
            if "STMT" in node_label or "CLAUSE" in node_label: icon = "►"
            elif "OPERATOR" in node_label or "JOIN" in node_label: icon = "◆"
            elif "COLUMN" in node_label or "TABLE" in node_label or "FIELD" in node_label: icon = "●"

            while stack and stack[-1][0] >= depth:
                stack.pop()

            parent_id = stack[-1][1] if stack else root_id
            item_id = self.ast_tree.insert(parent_id, tk.END, text=f" {icon} {node_label}", open=True)
            stack.append((depth, item_id))

    def load_sample(self, sample_name: str):
        samples = {
            "Basic SELECT Query": "SELECT u.id, u.name, u.email\nFROM users u\nWHERE u.age >= 18 AND u.status = 'ACTIVE';",
            "SELECT with JOIN & GROUP BY": "SELECT d.department_name, COUNT(e.id) AS total_employees, AVG(e.salary) AS avg_salary\nFROM employees e\nINNER JOIN departments d ON e.dept_id = d.id\nWHERE e.is_active = 1\nGROUP BY d.department_name\nHAVING COUNT(e.id) > 5\nORDER BY avg_salary DESC\nLIMIT 10;",
            "CREATE TABLE with Constraints": "CREATE TABLE orders (\n    order_id INT PRIMARY KEY AUTO_INCREMENT,\n    user_id INT NOT NULL,\n    total_amount DECIMAL(10,2) DEFAULT 0.00,\n    order_date TIMESTAMP,\n    FOREIGN KEY (user_id) REFERENCES users(id)\n);",
            "INSERT INTO Values": "INSERT INTO users (name, age, status)\nVALUES \n    ('Alice', 25, 'ACTIVE'),\n    ('Bob', 30, 'PENDING');",
            "Transaction Control (TCL)": "BEGIN TRANSACTION;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;",
            "Invalid Syntax Error Demo": "SELECT name, email FROM users WHERE age >= ;",
        }

        query = samples.get(sample_name, "")
        self.editor.delete("1.0", tk.END)
        self.editor.insert(tk.END, query)

    def open_file(self):
        path = filedialog.askopenfilename(filetypes=[("SQL Files", "*.sql"), ("All Files", "*.*")])
        if path:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                content = f.read()
            self.editor.delete("1.0", tk.END)
            self.editor.insert(tk.END, content)

    def clear_editor(self):
        self.editor.delete("1.0", tk.END)
        self.console_output.delete("1.0", tk.END)
        for item in self.ast_tree.get_children():
            self.ast_tree.delete(item)
        self.status_badge.config(text=" READY ", bg="#61afef", fg="#1e1e1e")


if __name__ == "__main__":
    root = tk.Tk()
    app = SQLValidatorApp(root)
    root.mainloop()
