
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 125
#define YY_END_OF_BUFFER 126
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[439] =
    {   0,
        0,    0,  126,  124,    1,    2,  124,  124,  112,  124,
      116,  117,  110,  108,  114,  109,  118,  111,  120,  115,
      106,  102,  107,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  124,    1,  103,    0,
      123,    0,    0,  122,    0,    3,    0,    0,  120,  104,
      105,  119,  119,  119,  119,   16,  119,  119,  119,  119,
      119,  119,    9,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   36,   83,   85,  119,  119,  119,  119,  119,

      119,  119,  119,  119,  119,   75,   81,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
       33,  119,  119,  119,  119,  119,  119,  113,    3,    0,
        0,  121,   28,   18,  119,   80,   12,  119,   99,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,   91,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,   48,  119,   38,  119,  119,
      119,  101,  100,  119,   41,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,   23,  119,

       98,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,    4,  119,  119,  119,  119,  119,
       66,   62,   87,   56,  119,   67,  119,  119,  119,  119,
      119,  119,   63,  119,  119,  119,   13,  119,  119,   30,
       90,  119,  119,  119,  119,    6,   72,  119,  119,  119,
      119,  119,  119,   20,   68,   70,   82,  119,  119,   42,
      119,  119,  119,  119,  119,  119,   60,  119,  119,  119,
      119,  119,  119,  119,  119,   57,   89,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,   88,  119,   27,
      119,   92,  119,  119,  119,   45,  119,  119,  119,   97,

      119,   74,  119,  119,  119,  119,  119,  119,  119,  119,
       58,  119,    8,  119,   35,   69,  119,  119,  119,   14,
      119,  119,  119,  119,   11,   73,  119,  119,  119,   71,
      119,  119,  119,  119,   26,  119,  119,  119,  119,   77,
      119,  119,   76,   21,  119,    7,  119,  119,   49,  119,
       34,   94,  119,   25,  119,  119,  119,   24,  119,   59,
       79,   86,  119,   10,   19,  119,  119,   29,   52,  119,
       15,  119,  119,   32,  119,  119,    5,  119,  119,  119,
      119,  119,   43,   22,   21,  119,  119,   84,   62,  119,
      119,   61,   44,  119,   39,   48,  119,   53,   37,  119,

      119,  119,  119,  119,   51,  119,  119,   55,  119,  119,
       64,   17,  119,  119,   95,  119,   50,  119,  119,   31,
       54,  119,  119,   78,  119,   96,   65,  119,  119,   46,
       40,  119,  119,   93,  119,  119,   47,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   17,
       16,   16,   16,   16,   16,   16,   16,    1,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
        1,   48,    1,    1,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   47,    1,   75,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1
    } ;

static const flex_int16_t yy_base[444] =
    {   0,
        0,    0,  264,  880,  259,  880,  215,   71,  880,   70,
      880,  880,  880,  880,  880,  219,  880,  216,   64,  880,
       62,  880,  198,   95,   68,  111,   67,   78,  110,   40,
       62,  127,   51,   62,  127,  157,  128,  149,   57,    0,
      170,  175,  224,  168,   77,   79,  114,  184,  880,   97,
      880,  170,  162,  880,  157,    0,  149,   69,  197,  880,
      880,    0,  130,  161,  174,  196,  182,  210,  211,  212,
      205,  206,    0,  203,  233,  208,  223,  253,  206,  268,
      209,  220,  240,  254,  271,  273,  262,  260,  264,  269,
      269,  263,    0,  307,    0,  279,  264,  284,  281,  267,

      281,  293,  280,  317,  308,    0,  320,  311,  323,  332,
      327,  323,  314,  325,  339,  328,  341,  320,  342,  337,
        0,  355,  344,  363,  361,  365,  375,  880,    0,  100,
       80,   75,    0,    0,  377,    0,    0,  370,    0,  377,
      364,  379,  387,  378,  386,  374,  390,  392,  375,  384,
      380,  386,  400,  383,  398,  397,  406,  404,  409,  403,
      424,  416,  428,    0,  431,  419,  438,  436,  429,  431,
      423,  436,  441,  442,  443,  444,  436,    0,  432,  448,
      446,    0,    0,  447,    0,  445,  460,  439,  458,  463,
      466,  470,  483,  488,  484,  482,  490,  492,    0,  486,

        0,  487,  480,  487,  497,  478,  490,  491,  491,  508,
      497,  491,  510,  500,  880,  497,   60,  505,  516,  510,
        0,  530,    0,    0,  527,    0,  531,  536,  528,  530,
      531,  534,  534,  542,  535,  537,    0,  549,  547,    0,
        0,  544,  541,  542,  555,    0,    0,  549,  553,  544,
      551,  552,  573,    0,    0,    0,    0,  551,  568,    0,
      570,  559,  589,  582,  583,  603,    0,  588,  594,  589,
      608,  595,  609,  601,  609,    0,    0,  596,  607,  598,
      615,  606,  600,  603,  617,  620,  618,    0,  622,    0,
      621,    0,  626,  613,  635,    0,  633,  630,  638,    0,

      652,    0,  651,  661,  651,  660,  652,  662,  648,  650,
        0,  663,    0,  664,    0,    0,  652,  668,  655,    0,
      651,  659,  670,  660,    0,    0,  663,  677,  678,    0,
      685,  672,  669,  683,    0,  683,  692,  711,  712,    0,
      711,  713,    0,  700,  720,    0,  708,  709,    0,  710,
        0,    0,  724,    0,  713,  715,  708,    0,  726,    0,
        0,    0,  716,    0,    0,  714,  728,    0,    0,  732,
        0,  711,  723,    0,  735,  730,    0,  728,  742,  725,
      745,  739,    0,    0,    0,  744,  765,    0,    0,  760,
      767,    0,    0,  754,    0,    0,  772,    0,    0,  774,

      767,  765,  760,  768,    0,  762,  778,   88,  766,  771,
        0,    0,  766,  783,    0,  769,    0,  775,  783,    0,
        0,  788,  774,    0,  776,    0,    0,  783,  786,    0,
        0,  787,  799,    0,  801,  798,    0,  880,  867,  870,
       97,  873,  876
    } ;

static const flex_int16_t yy_def[444] =
    {   0,
      438,    1,  438,  438,  438,  438,  438,  439,  438,  440,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  438,  438,  438,  439,
      438,  439,  440,  438,  440,  442,  443,  438,  438,  438,
      438,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,

      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  438,  442,  443,
      443,  438,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,

      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  438,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,

      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,

      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,    0,  438,  438,
      438,  438,  438
    } ;

static const flex_int16_t yy_nxt[956] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   40,   40,   40,    4,   40,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   40,   40,   47,   51,   54,   58,   91,   59,
       59,   60,   49,   92,  132,  132,   96,   97,   79,  131,
      132,  132,   80,   69,  215,  109,   81,   70,  126,   62,

       71,   51,   82,   72,  421,   83,   91,  127,  291,  131,
       84,   92,   85,   73,   96,   97,   79,   55,   52,   63,
       80,   69,   86,  109,   81,   70,  126,   64,   71,   65,
       82,   72,   74,   83,   66,  127,   67,   68,   84,   75,
       85,   73,   87,   76,   52,   88,   77,   63,   89,   78,
       86,   90,   98,   93,  133,   64,   99,   65,  131,  438,
       74,   94,   66,  103,   67,   68,   95,   75,   54,  104,
       87,   76,  438,   88,   77,  105,   89,   78,  100,   90,
       98,   93,  133,  106,   99,   48,  101,  107,  128,   94,
      108,  103,  102,  134,   95,  110,  113,  104,  136,  111,

      114,  135,  123,  105,  124,  112,  100,  125,  115,   55,
       58,  106,   59,   59,  101,  107,  116,   61,  108,  137,
      102,  134,  138,  110,  113,   57,  136,  111,  114,  135,
      123,   56,  124,  112,   49,  125,  115,  139,  140,  142,
      143,  144,  145,  148,  116,  117,  155,  137,  160,  118,
      138,  141,  119,  120,  146,  149,  150,  151,  147,  121,
       48,  161,  122,  438,  152,  139,  140,  142,  143,  144,
      145,  148,  438,  117,  155,  162,  160,  118,  153,  141,
      119,  120,  146,  149,  150,  151,  147,  121,  154,  161,
      122,  156,  152,  163,  157,  164,  165,  167,  168,  169,

      158,  170,  166,  162,  171,  172,  153,  159,  177,  178,
      179,  182,  180,  438,  181,  183,  154,  184,  438,  156,
      185,  163,  157,  164,  165,  167,  168,  169,  158,  170,
      166,  173,  171,  172,  188,  159,  177,  178,  179,  182,
      180,  174,  181,  183,  189,  184,  175,  176,  185,  186,
      187,  190,  191,  192,  195,  196,  197,  198,  193,  173,
      200,  201,  188,  202,  203,  199,  194,  204,  438,  174,
      205,  206,  189,  209,  175,  176,  207,  186,  187,  190,
      191,  192,  195,  196,  197,  198,  193,  210,  200,  201,
      211,  202,  203,  199,  194,  204,  208,  212,  205,  206,

      214,  209,  216,  213,  207,  217,  218,  219,  220,  221,
      222,  223,  224,  225,  226,  210,  227,  228,  211,  229,
      230,  231,  232,  233,  208,  212,  234,  235,  214,  236,
      216,  213,  237,  217,  218,  219,  220,  221,  222,  223,
      224,  225,  226,  238,  227,  228,  239,  229,  230,  231,
      232,  233,  240,  241,  234,  235,  242,  236,  243,  244,
      237,  245,  246,  247,  248,  249,  250,  251,  252,  253,
      255,  238,  256,  257,  239,  258,  259,  260,  263,  254,
      240,  241,  261,  264,  242,  262,  243,  244,  265,  245,
      246,  247,  248,  249,  250,  251,  252,  253,  255,  266,

      256,  257,  267,  258,  259,  260,  263,  254,  268,  269,
      261,  264,  270,  262,  271,  272,  265,  273,  274,  275,
      276,  277,  278,  279,  280,  281,  282,  266,  283,  284,
      267,  285,  286,  287,  288,  290,  268,  269,  289,  292,
      270,  293,  271,  272,  294,  273,  274,  275,  276,  277,
      278,  279,  280,  281,  282,  295,  283,  284,  296,  285,
      286,  287,  288,  290,  297,  298,  289,  292,  299,  293,
      300,  301,  294,  302,  303,  304,  305,  306,  307,  308,
      309,  310,  311,  295,  312,  313,  296,  314,  315,  316,
      317,  320,  297,  298,  321,  322,  299,  323,  300,  301,

      318,  302,  303,  304,  305,  306,  307,  308,  309,  310,
      311,  319,  312,  313,  324,  314,  315,  316,  317,  320,
      325,  326,  321,  322,  327,  323,  328,  329,  318,  330,
      331,  332,  333,  334,  335,  336,  337,  338,  339,  319,
      340,  341,  324,  342,  343,  344,  345,  346,  325,  326,
      347,  348,  327,  349,  328,  329,  350,  330,  331,  332,
      333,  334,  335,  336,  337,  338,  339,  351,  340,  341,
      352,  342,  343,  344,  345,  346,  353,  354,  347,  348,
      355,  349,  356,  357,  350,  358,  359,  360,  361,  362,
      363,  364,  365,  366,  367,  351,  368,  369,  352,  370,

      371,  372,  373,  374,  353,  354,  375,  376,  355,  377,
      356,  357,  378,  358,  359,  360,  361,  362,  363,  364,
      365,  366,  367,  379,  368,  369,  380,  370,  371,  372,
      373,  374,  381,  382,  375,  376,  383,  377,  384,  385,
      378,  386,  387,  388,  389,  390,  391,  392,  393,  394,
      395,  379,  396,  397,  380,  398,  399,  400,  401,  402,
      381,  382,  403,  404,  383,  405,  384,  385,  406,  386,
      387,  388,  389,  390,  391,  392,  393,  394,  395,  407,
      396,  397,  408,  398,  399,  400,  401,  402,  409,  410,
      403,  404,  411,  405,  412,  413,  406,  414,  415,  416,

      417,  418,  419,  420,  422,  423,  424,  407,  425,  426,
      408,  427,  428,  429,  430,  431,  409,  410,  432,  433,
      411,  434,  412,  413,  435,  414,  415,  416,  417,  418,
      419,  420,  422,  423,  424,  436,  425,  426,  437,  427,
      428,  429,  430,  431,  438,  438,  432,  433,  438,  434,
      438,  438,  435,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  436,  438,  438,  437,   50,   50,   50,
       53,   53,   53,  129,  438,  129,  130,  130,  130,    3,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438
    } ;

static const flex_int16_t yy_chk[956] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,   10,   19,   30,   19,
       19,   21,   21,   31,   58,   58,   33,   34,   27,  131,
      132,  132,   27,   25,  131,   39,   27,   25,   45,  441,

       25,   50,   27,   25,  408,   27,   30,   46,  217,  130,
       28,   31,   28,   25,   33,   34,   27,   10,    8,   24,
       27,   25,   28,   39,   27,   25,   45,   24,   25,   24,
       27,   25,   26,   27,   24,   46,   24,   24,   28,   26,
       28,   25,   29,   26,   50,   29,   26,   24,   29,   26,
       28,   29,   35,   32,   63,   24,   35,   24,   57,   55,
       26,   32,   24,   37,   24,   24,   32,   26,   53,   37,
       29,   26,   52,   29,   26,   38,   29,   26,   36,   29,
       35,   32,   63,   38,   35,   48,   36,   38,   47,   32,
       38,   37,   36,   64,   32,   41,   42,   37,   65,   41,

       42,   64,   44,   38,   44,   41,   36,   44,   42,   53,
       59,   38,   59,   59,   36,   38,   42,   23,   38,   66,
       36,   64,   67,   41,   42,   18,   65,   41,   42,   64,
       44,   16,   44,   41,    7,   44,   42,   68,   69,   70,
       71,   72,   74,   76,   42,   43,   79,   66,   81,   43,
       67,   69,   43,   43,   75,   77,   77,   77,   75,   43,
        5,   82,   43,    3,   77,   68,   69,   70,   71,   72,
       74,   76,    0,   43,   79,   83,   81,   43,   78,   69,
       43,   43,   75,   77,   77,   77,   75,   43,   78,   82,
       43,   80,   77,   84,   80,   85,   86,   87,   88,   89,

       80,   90,   86,   83,   91,   92,   78,   80,   96,   97,
       98,  100,   99,    0,   99,  101,   78,  102,    0,   80,
      103,   84,   80,   85,   86,   87,   88,   89,   80,   90,
       86,   94,   91,   92,  105,   80,   96,   97,   98,  100,
       99,   94,   99,  101,  107,  102,   94,   94,  103,  104,
      104,  108,  109,  110,  111,  112,  113,  114,  110,   94,
      115,  116,  105,  117,  118,  114,  110,  119,    0,   94,
      120,  120,  107,  123,   94,   94,  122,  104,  104,  108,
      109,  110,  111,  112,  113,  114,  110,  124,  115,  116,
      125,  117,  118,  114,  110,  119,  122,  126,  120,  120,

      127,  123,  135,  126,  122,  138,  140,  141,  142,  143,
      144,  145,  146,  147,  148,  124,  149,  150,  125,  151,
      152,  153,  154,  155,  122,  126,  156,  157,  127,  158,
      135,  126,  159,  138,  140,  141,  142,  143,  144,  145,
      146,  147,  148,  160,  149,  150,  161,  151,  152,  153,
      154,  155,  162,  163,  156,  157,  165,  158,  166,  167,
      159,  168,  169,  170,  171,  172,  173,  174,  175,  176,
      177,  160,  179,  180,  161,  181,  184,  186,  188,  176,
      162,  163,  187,  189,  165,  187,  166,  167,  190,  168,
      169,  170,  171,  172,  173,  174,  175,  176,  177,  191,

      179,  180,  192,  181,  184,  186,  188,  176,  193,  194,
      187,  189,  195,  187,  196,  197,  190,  198,  200,  202,
      203,  204,  205,  206,  207,  208,  209,  191,  209,  210,
      192,  211,  212,  213,  214,  216,  193,  194,  214,  218,
      195,  219,  196,  197,  220,  198,  200,  202,  203,  204,
      205,  206,  207,  208,  209,  222,  209,  210,  225,  211,
      212,  213,  214,  216,  227,  228,  214,  218,  229,  219,
      230,  231,  220,  232,  233,  234,  235,  236,  238,  239,
      242,  243,  244,  222,  245,  248,  225,  249,  250,  251,
      252,  258,  227,  228,  259,  261,  229,  262,  230,  231,

      253,  232,  233,  234,  235,  236,  238,  239,  242,  243,
      244,  253,  245,  248,  263,  249,  250,  251,  252,  258,
      264,  265,  259,  261,  266,  262,  268,  269,  253,  270,
      271,  272,  273,  274,  275,  278,  279,  280,  281,  253,
      282,  283,  263,  284,  285,  286,  287,  289,  264,  265,
      291,  293,  266,  294,  268,  269,  295,  270,  271,  272,
      273,  274,  275,  278,  279,  280,  281,  297,  282,  283,
      298,  284,  285,  286,  287,  289,  299,  301,  291,  293,
      303,  294,  304,  305,  295,  306,  307,  308,  309,  310,
      312,  314,  317,  318,  319,  297,  321,  322,  298,  323,

      324,  327,  328,  329,  299,  301,  331,  332,  303,  333,
      304,  305,  334,  306,  307,  308,  309,  310,  312,  314,
      317,  318,  319,  336,  321,  322,  337,  323,  324,  327,
      328,  329,  338,  339,  331,  332,  341,  333,  342,  344,
      334,  345,  347,  348,  350,  353,  355,  356,  357,  359,
      363,  336,  366,  367,  337,  370,  372,  373,  375,  376,
      338,  339,  378,  379,  341,  380,  342,  344,  381,  345,
      347,  348,  350,  353,  355,  356,  357,  359,  363,  382,
      366,  367,  386,  370,  372,  373,  375,  376,  387,  390,
      378,  379,  391,  380,  394,  397,  381,  400,  401,  402,

      403,  404,  406,  407,  409,  410,  413,  382,  414,  416,
      386,  418,  419,  422,  423,  425,  387,  390,  428,  429,
      391,  432,  394,  397,  433,  400,  401,  402,  403,  404,
      406,  407,  409,  410,  413,  435,  414,  416,  436,  418,
      419,  422,  423,  425,    0,    0,  428,  429,    0,  432,
        0,    0,  433,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  435,    0,    0,  436,  439,  439,  439,
      440,  440,  440,  442,    0,  442,  443,  443,  443,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[126] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sql_lexer.l"
#line 2 "sql_lexer.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ast.h"
#include "sql_parser.tab.h"

int yycolumn = 1;
extern int g_show_tokens;

#define YY_USER_ACTION \
    if (g_show_tokens) { \
        printf("[TOKEN] Lexeme: '%-15s' Line: %d Col: %d\n", \
               yytext, yylineno, yycolumn); \
    } \
    yycolumn += yyleng;

static char* clean_string(const char *str) {
    size_t len = strlen(str);
    if (len >= 2 && ((str[0] == '\'' && str[len-1] == '\'') || (str[0] == '"' && str[len-1] == '"'))) {
        char *cleaned = (char *)malloc(len - 1);
        strncpy(cleaned, str + 1, len - 2);
        cleaned[len - 2] = '\0';
        return cleaned;
    }
    return strdup(str);
}

#line 859 "lex.yy.c"
#line 860 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 35 "sql_lexer.l"


#line 1080 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 439 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 880 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "sql_lexer.l"
{ /* Skip whitespace including non-breaking spaces */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 38 "sql_lexer.l"
{ yycolumn = 1; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "sql_lexer.l"
{ /* Skip single-line comments */ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 42 "sql_lexer.l"
{ 
                            for (int i = 0; yytext[i] != '\0'; i++) {
                                if (yytext[i] == '\n') {
                                    yylineno++;
                                    yycolumn = 1;
                                }
                            }
                          }
	YY_BREAK
/* Keywords */
case 5:
YY_RULE_SETUP
#line 52 "sql_lexer.l"
{ return SELECT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "sql_lexer.l"
{ return FROM; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "sql_lexer.l"
{ return WHERE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "sql_lexer.l"
{ return GROUP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "sql_lexer.l"
{ return BY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "sql_lexer.l"
{ return HAVING; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 58 "sql_lexer.l"
{ return ORDER; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 59 "sql_lexer.l"
{ return ASC; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "sql_lexer.l"
{ return DESC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "sql_lexer.l"
{ return LIMIT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "sql_lexer.l"
{ return OFFSET; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "sql_lexer.l"
{ return AS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "sql_lexer.l"
{ return DISTINCT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "sql_lexer.l"
{ return ALL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 67 "sql_lexer.l"
{ return INSERT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "sql_lexer.l"
{ return INTO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "sql_lexer.l"
{ return VALUES; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "sql_lexer.l"
{ return UPDATE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "sql_lexer.l"
{ return SET; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 72 "sql_lexer.l"
{ return DELETE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "sql_lexer.l"
{ return CREATE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "sql_lexer.l"
{ return TABLE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "sql_lexer.l"
{ return ALTER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "sql_lexer.l"
{ return ADD; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 78 "sql_lexer.l"
{ return MODIFY; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "sql_lexer.l"
{ return DROP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "sql_lexer.l"
{ return TRUNCATE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "sql_lexer.l"
{ return RENAME; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 82 "sql_lexer.l"
{ return TO; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 83 "sql_lexer.l"
{ return COLUMN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 84 "sql_lexer.l"
{ return INDEX; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 85 "sql_lexer.l"
{ return IF_KW; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "sql_lexer.l"
{ return PRIMARY; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 88 "sql_lexer.l"
{ return KEY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "sql_lexer.l"
{ return FOREIGN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "sql_lexer.l"
{ return REFERENCES; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "sql_lexer.l"
{ return NOT_KW; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "sql_lexer.l"
{ return NULL_KW; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "sql_lexer.l"
{ return UNIQUE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "sql_lexer.l"
{ return DEFAULT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "sql_lexer.l"
{ return CHECK; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "sql_lexer.l"
{ return CONSTRAINT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "sql_lexer.l"
{ return AUTO_INCREMENT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 99 "sql_lexer.l"
{ return INT_TYPE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 100 "sql_lexer.l"
{ return BIGINT_TYPE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 101 "sql_lexer.l"
{ return SMALLINT_TYPE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 102 "sql_lexer.l"
{ return TINYINT_TYPE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 103 "sql_lexer.l"
{ return NUMBER_TYPE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 104 "sql_lexer.l"
{ return NUMERIC_TYPE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 105 "sql_lexer.l"
{ return VARCHAR2_TYPE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 106 "sql_lexer.l"
{ return VARCHAR_TYPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 107 "sql_lexer.l"
{ return CHAR_TYPE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 108 "sql_lexer.l"
{ return TEXT_TYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 109 "sql_lexer.l"
{ return FLOAT_TYPE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 110 "sql_lexer.l"
{ return DOUBLE_TYPE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 111 "sql_lexer.l"
{ return REAL_TYPE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 112 "sql_lexer.l"
{ return DECIMAL_TYPE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 113 "sql_lexer.l"
{ return BOOLEAN_TYPE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 114 "sql_lexer.l"
{ return DATE_TYPE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 115 "sql_lexer.l"
{ return DATETIME_TYPE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 116 "sql_lexer.l"
{ return TIMESTAMP_TYPE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 117 "sql_lexer.l"
{ return BLOB_TYPE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 118 "sql_lexer.l"
{ return CLOB_TYPE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "sql_lexer.l"
{ return JOIN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 121 "sql_lexer.l"
{ return INNER; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "sql_lexer.l"
{ return LEFT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 123 "sql_lexer.l"
{ return RIGHT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 124 "sql_lexer.l"
{ return FULL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 125 "sql_lexer.l"
{ return OUTER; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 126 "sql_lexer.l"
{ return CROSS; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 127 "sql_lexer.l"
{ return ON; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 128 "sql_lexer.l"
{ return USING; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 130 "sql_lexer.l"
{ return UNION; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 131 "sql_lexer.l"
{ return INTERSECT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "sql_lexer.l"
{ return EXCEPT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 134 "sql_lexer.l"
{ return AND; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 135 "sql_lexer.l"
{ return OR; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 136 "sql_lexer.l"
{ return LIKE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 137 "sql_lexer.l"
{ return IN; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 138 "sql_lexer.l"
{ return BETWEEN; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 139 "sql_lexer.l"
{ return IS; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 140 "sql_lexer.l"
{ return EXISTS; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 141 "sql_lexer.l"
{ return CASE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 142 "sql_lexer.l"
{ return WHEN; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 143 "sql_lexer.l"
{ return THEN; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 144 "sql_lexer.l"
{ return ELSE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 145 "sql_lexer.l"
{ return END; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 147 "sql_lexer.l"
{ return BEGIN_KW; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 148 "sql_lexer.l"
{ return TRANSACTION; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 149 "sql_lexer.l"
{ return COMMIT; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 150 "sql_lexer.l"
{ return ROLLBACK; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 151 "sql_lexer.l"
{ return SAVEPOINT; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 153 "sql_lexer.l"
{ return COUNT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 154 "sql_lexer.l"
{ return SUM; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 155 "sql_lexer.l"
{ return AVG; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 156 "sql_lexer.l"
{ return MIN; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 157 "sql_lexer.l"
{ return MAX; }
	YY_BREAK
/* Operators */
case 102:
YY_RULE_SETUP
#line 160 "sql_lexer.l"
{ return EQ; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 161 "sql_lexer.l"
{ return NE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 162 "sql_lexer.l"
{ return LE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 163 "sql_lexer.l"
{ return GE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 164 "sql_lexer.l"
{ return LT; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 165 "sql_lexer.l"
{ return GT; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 166 "sql_lexer.l"
{ return PLUS; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 167 "sql_lexer.l"
{ return MINUS; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 168 "sql_lexer.l"
{ return STAR; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 169 "sql_lexer.l"
{ return SLASH; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 170 "sql_lexer.l"
{ return MOD; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 171 "sql_lexer.l"
{ return CONCAT; }
	YY_BREAK
/* Delimiters */
case 114:
YY_RULE_SETUP
#line 174 "sql_lexer.l"
{ return COMMA; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 175 "sql_lexer.l"
{ return SEMICOLON; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 176 "sql_lexer.l"
{ return LPAREN; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 177 "sql_lexer.l"
{ return RPAREN; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 178 "sql_lexer.l"
{ return DOT; }
	YY_BREAK
/* Identifiers */
case 119:
YY_RULE_SETUP
#line 181 "sql_lexer.l"
{
    yylval.str = strdup(yytext);
    return IDENTIFIER;
}
	YY_BREAK
/* Numeric Literals */
case 120:
YY_RULE_SETUP
#line 187 "sql_lexer.l"
{
    yylval.str = strdup(yytext);
    return INT_LITERAL;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 192 "sql_lexer.l"
{
    yylval.str = strdup(yytext);
    return FLOAT_LITERAL;
}
	YY_BREAK
/* String Literals */
case 122:
/* rule 122 can match eol */
YY_RULE_SETUP
#line 198 "sql_lexer.l"
{
    yylval.str = clean_string(yytext);
    return STRING_LITERAL;
}
	YY_BREAK
case 123:
/* rule 123 can match eol */
YY_RULE_SETUP
#line 203 "sql_lexer.l"
{
    yylval.str = clean_string(yytext);
    return STRING_LITERAL;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 208 "sql_lexer.l"
{
    printf("[LEX ERROR] Line %d, Column %d: Unrecognized character '%s'\n", yylineno, yycolumn - (int)yyleng, yytext);
    return yytext[0];
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 213 "sql_lexer.l"
ECHO;
	YY_BREAK
#line 1807 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 439 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 439 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 438);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 213 "sql_lexer.l"


